### ISSUE TITLE
Fix PELT/segment cost functions so Julia output matches R output

### ISSUE THREAD

**Issue by fairbrot** [STOR-i/Changepoints.jl#17]
I've written an R comparison test. The PELT output for the Normal segment costs seems to match but the others don't. In the case of the Gamma comparison I did not know what shape parameter to use. Also, I could not run a test for the Nonparametric cost functions as the changepoint file for this contained much more output than just the changepoints.

The tests can be redone by running `Pkg.test("Changepoints")`

``` julia
Test Normal mean change...
Changepoint distribution is Normal with changing mean and fixed variance
    Success!
Test Normal variance change...
Changepoint distribution is Normal with fixed mean and changing variance
    Success!
Test Normal mean and variance chaange...
Changepoint distribution is Normal with changing mean and changing variance
    Success!
Test Poisson change...
Changepoint distribution is Poisson with changing mean
Fail:
    R Changepoints: [0,85,228,360,438,500]
    Julia Changepoints: [0,85,228,360,438]
Test Poisson change...
Changepoint distribution is Exponential with changing mean
Fail:
    R Changepoints: [0,228,361]
    Julia Changepoints: [0,228,361,424]
Test Gamma rate change...
Changepoint distribution is Gamma with fixed shape and changing rate
Fail:
    R Changepoints: [0,83,228,360,438,500]
    Julia Changepoints: [0,83,228,360,438]
```

**Comment by kayleahaynes** [comment]
Fixed.  The issues with Poisson and Gamma were that the R cpt package also included n in the list of changepoints.  The julia Exponential cost function was slightly different to the R cost function.  I have also fixed nonparametric - I had saved the wrong information in the cpt file.

**Comment by fairbrot** [comment]
Great, thanks!
