### ISSUE TITLE
NormalMeanChange is not defined when running example code

### ISSUE THREAD

**Issue by av-maslov** [STOR-i/Changepoints.jl#32]
Hello,
When running an example for PELT from the documentation the error is encountered 

```
julia> seg_cost = NormalMeanChange(data, s)  
ERROR: UndefVarError: NormalMeanChange not defined
```

Thank you.

**Comment by fairbrot** [comment]
Hi, thanks for pointing this out. This is a mistake in the README.md file. You should use `NormalMeanSegment` rather than `NormalMeanChange`. I've now fixed this in the documentation.
