### ISSUE TITLE
Create R data sets for unit testing

### ISSUE THREAD

**Issue by fairbrot** [STOR-i/Changepoints.jl#4]
- Files of time series for different changes
- Output of R algorithms in separate files

This data should be put into the directory test/Rdata

**Comment by kayleahaynes** [comment]
I have created csv files of data sets for each of the distributions and possible types of changes.  I have also included the resulting changepoints using R and the penalty 2_log(n)_p where p is the number of parameters.

**Comment by fairbrot** [comment]
Great, thanks for this. I assume that the Changepoints have been found with PELT (rather than BS) so I will append PELT to the cps file names to make this clear. For the Gamma, what type of change is being detected here: change in shape or change in rate/scale? Also Nonparametric has an extra parameter K: what value did you use for this?

**Comment by kayleahaynes** [comment]
Oh yeah that's a good point they have.  For gamma it's a change in rate with constant shape... I'm not sure the changepoint package on R looks at change in scale.

I have my code saved for creating these if you would prefer these in a different format as well :)

Kaylea

Sent from my iPhone

On 20 Mar 2015, at 14:02, "Jamie Fairbrother" <notifications@github.com<mailto:notifications@github.com>> wrote:

Great, thanks for this. I assume that the Changepoints have been found with PELT so I will append PELT to the cps file names to make this clear. Also, for the Gamma, what type of change is being detected here: change in shape or change in rate/scale?

**Comment by fairbrot** [comment]
If you could put the R file in Test_Files that would be great.
